"""PDF generation for lesson slideshows"""

from typing import Any
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import io

from slide_templates import SlideTemplates
from lesson_parser import LessonParser


class PDFGenerator:
    def __init__(self, output_path: str, lesson_parser: LessonParser):
        self.output_path = output_path
        self.lesson = lesson_parser
        self.templates = SlideTemplates()
        self.styles = self._setup_styles()

    def _setup_styles(self) -> dict[str, Any]:
        styles = getSampleStyleSheet()

        custom_styles = {
            "title": ParagraphStyle(
                "CustomTitle",
                parent=styles["Heading1"],
                fontSize=36,
                textColor=self.templates.COLOR_PRIMARY,
                spaceAfter=30,
                alignment=1,  # Center
            ),
            "subtitle": ParagraphStyle(
                "CustomSubtitle",
                parent=styles["Heading2"],
                fontSize=18,
                textColor=self.templates.COLOR_TEXT,
                alignment=1,  # Center
            ),
            "step_title": ParagraphStyle(
                "StepTitle",
                parent=styles["Heading2"],
                fontSize=24,
                textColor=self.templates.COLOR_PRIMARY,
                spaceBefore=10,
                spaceAfter=10,
            ),
            "step_instruction": ParagraphStyle(
                "StepInstruction",
                parent=styles["BodyText"],
                fontSize=14,
                textColor=self.templates.COLOR_TEXT,
                spaceBefore=10,
                spaceAfter=20,
                leading=18,
            ),
            "body_text": ParagraphStyle(
                "BodyText",
                parent=styles["BodyText"],
                fontSize=12,
                textColor=self.templates.COLOR_TEXT,
                leading=14,
            ),
            "footer": ParagraphStyle(
                "Footer",
                parent=styles["BodyText"],
                fontSize=10,
                textColor=colors.gray,
                alignment=1,  # Center
            ),
        }

        return custom_styles

    def generate(self) -> None:
        story = []

        self._add_title_slide(story)
        story.append(PageBreak())

        for step in self.lesson.steps:
            self._add_step_slide(story, step)
            story.append(PageBreak())

        self._add_summary_slide(story)

        doc = SimpleDocTemplate(
            self.output_path,
            pagesize=letter,
            rightMargin=self.templates.MARGIN,
            leftMargin=self.templates.MARGIN,
            topMargin=self.templates.MARGIN,
            bottomMargin=self.templates.MARGIN,
        )

        doc.build(
            story,
            onFirstPage=self._add_page_header_footer,
            onLaterPages=self._add_page_header_footer,
        )

    def _add_page_header_footer(self, canvas_obj: canvas.Canvas, doc: Any) -> None:
        width, height = letter

        canvas_obj.saveState()

        canvas_obj.setFillColor(self.templates.COLOR_PRIMARY)
        canvas_obj.rect(0, height - 50, width, 50, fill=1, stroke=0)

        canvas_obj.setFillColor(colors.white)
        canvas_obj.setFont("Helvetica-Bold", 12)
        canvas_obj.drawCentredString(width / 2, height - 25, self.lesson.lesson_name)

        canvas_obj.setFillColor(colors.lightgrey)
        canvas_obj.line(0, self.templates.MARGIN, width, self.templates.MARGIN)

        canvas_obj.setFont("Helvetica", 8)
        canvas_obj.setFillColor(colors.gray)
        canvas_obj.drawCentredString(
            width / 2,
            self.templates.MARGIN / 2,
            "Generated by Embettered Slideshow Generator",
        )

        canvas_obj.restoreState()

    def _add_title_slide(self, story: list) -> None:
        coords = self.templates.get_title_slide_coords()

        story.append(Spacer(1, coords["title_y"] - 7 * inch))

        title = Paragraph(self.lesson.lesson_name, self.styles["title"])
        story.append(title)

        story.append(Spacer(1, 0.3 * inch))

        if self.lesson.description:
            subtitle = Paragraph(self.lesson.description, self.styles["subtitle"])
            story.append(subtitle)

        story.append(Spacer(1, 2 * inch))

        total_steps = self.lesson.get_step_count()
        info_text = (
            f"<b>{total_steps} Step Tutorial</b><br/>Embedded Systems Learning Platform"
        )
        info = Paragraph(info_text, self.styles["body_text"])
        story.append(info)

    def _add_step_slide(self, story: list, step: dict[str, Any]) -> None:
        coords = self.templates.get_step_slide_coords()

        step_num = step.get("step", 0)
        description = step.get("description", "")
        instruction = step.get("instruction", "")
        visuals = step.get("visuals", [])

        header_text = f"Step {step_num}: {description}"
        header = Paragraph(header_text, self.styles["step_title"])
        story.append(header)

        story.append(Spacer(1, 0.2 * inch))

        instruction_text = f"<b>Instruction:</b> {instruction}"
        instruction_para = Paragraph(instruction_text, self.styles["step_instruction"])
        story.append(instruction_para)

        if visuals:
            story.append(Spacer(1, 0.5 * inch))
            self._add_visuals(story, visuals)

    def _add_visuals(self, story: list, visuals: list[dict[str, Any]]) -> None:
        for visual in visuals:
            visual_data = self.templates.get_step_visual_data(visual)
            visual_type = visual_data["type"]

            if visual_type == "text":
                self._add_text_visual(story, visual_data)
            elif visual_type == "shape":
                self._add_shape_visual(story, visual_data)
            elif visual_type == "line":
                self._add_line_visual(story, visual_data)

    def _add_text_visual(self, story: list, visual_data: dict[str, Any]) -> None:
        x, y, width, height = self.templates.scale_coordinates(
            visual_data["x"],
            visual_data["y"],
            visual_data["width"],
            visual_data["height"],
        )

        text_style = ParagraphStyle(
            "VisualText",
            parent=self.styles["body_text"],
            fontSize=visual_data.get("font_size", 12) / 2,
            textColor=colors.Color(*[c / 255.0 for c in visual_data["color"]]),
        )

        text_para = Paragraph(visual_data["text"], text_style)
        story.append(text_para)
        story.append(Spacer(1, 0.1 * inch))

    def _add_shape_visual(self, story: list, visual_data: dict[str, Any]) -> None:
        shape_text = f"<b>[Shape: {visual_data.get('filename', 'Unknown')}]</b><br/>Position: ({visual_data['x']}, {visual_data['y']})<br/>Size: {visual_data['width']}x{visual_data['height']}"

        shape_style = ParagraphStyle(
            "ShapeInfo",
            parent=self.styles["body_text"],
            fontSize=10,
            textColor=self.templates.COLOR_ACCENT,
            backColor=self.templates.COLOR_LIGHT_BG,
            borderPadding=10,
        )

        shape_para = Paragraph(shape_text, shape_style)
        story.append(shape_para)
        story.append(Spacer(1, 0.2 * inch))

    def _add_line_visual(self, story: list, visual_data: dict[str, Any]) -> None:
        line_text = f"<b>[Wiring Line]</b><br/>From: ({visual_data['x']}, {visual_data['y']})<br/>Direction: {visual_data['width']}, {visual_data['height']}"

        line_style = ParagraphStyle(
            "LineInfo",
            parent=self.styles["body_text"],
            fontSize=10,
            textColor=colors.Color(*[c / 255.0 for c in visual_data["color"]]),
            backColor=self.templates.COLOR_LIGHT_BG,
            borderPadding=10,
        )

        line_para = Paragraph(line_text, line_style)
        story.append(line_para)
        story.append(Spacer(1, 0.2 * inch))

    def _add_summary_slide(self, story: list) -> None:
        coords = self.templates.get_summary_slide_coords()

        title = Paragraph("Lesson Summary", self.styles["title"])
        story.append(title)

        story.append(Spacer(1, 0.5 * inch))

        summary_parts = [f"<b>Lesson:</b> {self.lesson.lesson_name}"]

        if self.lesson.description:
            summary_parts.append(f"<b>Description:</b> {self.lesson.description}")

        summary_parts.append(f"<b>Total Steps:</b> {self.lesson.get_step_count()}")

        summary_parts.append("<br/><b>Steps Overview:</b>")
        for step in self.lesson.steps:
            step_num = step.get("step", 0)
            description = step.get("description", "")
            summary_parts.append(f"• Step {step_num}: {description}")

        summary_text = "<br/>".join(summary_parts)
        summary_para = Paragraph(summary_text, self.styles["body_text"])
        story.append(summary_para)

        story.append(Spacer(1, 1 * inch))

        completion_text = "<b>🎓 Congratulations!</b><br/>You have completed this lesson. Good luck with your embedded systems project!"
        completion_para = Paragraph(completion_text, self.styles["step_instruction"])
        story.append(completion_para)
